version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: website_backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python ./backend.py